### ISSUE TITLE
No module named 'crawler_util'

### ISSUE THREAD

**Issue by raffi92** [asmiller1989/Ethereum_Blockchain_Parser#6]
Hi,

When trying to run preprocessing.py it can't find the crawler_util module. From crawler_util import * isn't a solution...

Traceback (most recent call last):
  File "preprocess.py", line 9, in <module>
    from Crawler import Crawler
  File "./../Preprocessing/Crawler/__init__.py", line 1, in <module>
    from .Crawler import Crawler
  File "./../Preprocessing/Crawler/Crawler.py", line 4, in <module>
    import crawler_util
ModuleNotFoundError: No module named 'crawler_util'

**Comment by StevenHarlow** [comment]
I solved with adding `sys.path.append("./../Preprocessing/Crawler")` to preprocess.py line 7
